# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    php_errors:
        log:
            '!php/const \E_DEPRECATED': !php/const Psr\Log\LogLevel::ERROR
            '!php/const \E_USER_DEPRECATED': !php/const Psr\Log\LogLevel::ERROR
            '!php/const \E_NOTICE': !php/const Psr\Log\LogLevel::ERROR
            '!php/const \E_USER_NOTICE': !php/const Psr\Log\LogLevel::ERROR
            '!php/const \E_STRICT': !php/const Psr\Log\LogLevel::ERROR
            '!php/const \E_WARNING': !php/const Psr\Log\LogLevel::ERROR
            '!php/const \E_USER_WARNING': !php/const Psr\Log\LogLevel::ERROR
            '!php/const \E_COMPILE_WARNING': !php/const Psr\Log\LogLevel::ERROR
            '!php/const \E_CORE_WARNING': !php/const Psr\Log\LogLevel::ERROR
            '!php/const \E_USER_ERROR': !php/const Psr\Log\LogLevel::CRITICAL
            '!php/const \E_RECOVERABLE_ERROR': !php/const Psr\Log\LogLevel::CRITICAL
            '!php/const \E_COMPILE_ERROR': !php/const Psr\Log\LogLevel::CRITICAL
            '!php/const \E_PARSE': !php/const Psr\Log\LogLevel::CRITICAL
            '!php/const \E_ERROR': !php/const Psr\Log\LogLevel::CRITICAL
            '!php/const \E_CORE_ERROR': !php/const Psr\Log\LogLevel::CRITICAL
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
