nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: [ '*' ]
    allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
    allow_headers: [ 'Content-Type', 'Authorization', 'Preload', 'Fields' ]
    expose_headers: [ 'Link' ]
    max_age: 3600
  paths:
    '^/api/':
      origin_regex: true
      allow_origin: [ '*' ] # allow all origins
      allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
      allow_headers: [ '*' ] # allow all headers
      expose_headers: [ 'Link' ]
      max_age: 3600