vich_uploader:
  db_driver: orm

  mappings:
    avatar:
      uri_prefix: /media/avatar
      upload_destination: '%kernel.project_dir%/public/media/avatar'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    images:
      uri_prefix: /media/images
      upload_destination: '%kernel.project_dir%/public/media/images'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\UniqidNamer