vich_uploader:
  db_driver: orm

  mappings:
    avatar:
      uri_prefix: /media/avatar
      upload_destination: '%kernel.project_dir%/public/media/avatar'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    category:
      uri_prefix: /media/category
      upload_destination: '%kernel.project_dir%/public/media/category'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    news:
      uri_prefix: /media/news
      upload_destination: '%kernel.project_dir%/public/media/news'
        # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\UniqidNamer