vich_uploader:
  db_driver: orm

  mappings:
    avatar:
      uri_prefix: /images/avatar
      upload_destination: '%kernel.project_dir%/public/images/avatar'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    category:
      uri_prefix: /images/category
      upload_destination: '%kernel.project_dir%/public/images/category'
      # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    news:
      uri_prefix: /images/news
      upload_destination: '%kernel.project_dir%/public/images/news'
        # Will rename uploaded files using a uniqueid as a prefix.
      namer: Vich\UploaderBundle\Naming\UniqidNamer